name: pet_style_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0

  internet_connection_checker_plus: ^2.5.2

  searchfield: ^1.1.6

  # bloc
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3

  smooth_page_indicator: ^1.2.0
  flutter_svg: ^2.0.10

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  get_it: ^8.0.0
  go_router: ^14.3.0
  badges: ^3.1.2
  google_fonts: ^6.2.1


  fluttertoast: ^8.2.8
  
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3

  shared_preferences: ^2.3.2

  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  timezone: ^0.9.4

  dio: ^5.7.0

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3

  device_info_plus: ^11.1.0
  android_id: ^0.4.0
  package_info_plus: ^8.1.0
  flutter_local_notifications: ^17.2.3

  #logger
  talker: 4.4.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  
  #auth
  google_sign_in: ^6.2.1
  
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  date_picker_timeline: ^1.2.6
  pinput: ^5.0.0
  
  http_parser: ^4.0.2

  animate_do: ^3.3.4
  #chat
  socket_io_client: ^3.0.0

  #toast
  toastification: ^2.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_gen:
    output: lib/gen
    line_length: 80
    integrations:
      flutter_svg: true
      lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/json/
    - assets/fonts/
  fonts:
  - family: Jost
    fonts:
    - asset: assets/fonts/Jost-Regular.ttf
      weight: 400
    - asset: assets/fonts/Jost-Medium.ttf
      weight: 500
    - asset: assets/fonts/Jost-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Jost-Bold.ttf
      weight: 700
    - asset: assets/fonts/Jost-Light.ttf
      weight: 200
