// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7AhRiSjr23ZdJfBqFpMGaw7dqthLuDeA',
    appId: '1:855697215683:web:da959da9d46208c92c1276',
    messagingSenderId: '855697215683',
    projectId: 'petstyle',
    authDomain: 'petstyle.firebaseapp.com',
    storageBucket: 'petstyle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAxXlG-mIYbco0NNjJaMM5XhxpORyeGo',
    appId: '1:855697215683:android:885922326cd377822c1276',
    messagingSenderId: '855697215683',
    projectId: 'petstyle',
    storageBucket: 'petstyle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9J9n2tTdnjJCGJxVU1CJaeS2-IVt7Gs4',
    appId: '1:855697215683:ios:18e6cfee30ad2d922c1276',
    messagingSenderId: '855697215683',
    projectId: 'petstyle',
    storageBucket: 'petstyle.appspot.com',
    iosBundleId: 'dev.dextermd.petstyle',
  );
}
